version: "2"

networks:
  app-tier:
    driver: bridge

services:

  app:
    image: openmatchmaking/pathfinder:latest
    ports:
      - "9000:9000"
    environment:
      - LISTENED_IP=0.0.0.0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VHOST=vhost
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - app-tier
    tty: true

  rabbitmq_worker:
    image: rabbitmq-worker
    build:
      context: .
      dockerfile: ./rabbitmq-worker/Dockerfile
    volumes:
      - ./rabbitmq-worker:/code
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - app-tier
    tty: true

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  redis_commander_ui:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"

  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VHOST=vhost
    networks:
      - app-tier
